apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::697533197703:role/eksctl-eksctl-demo-nodegroup-ng-e-NodeInstanceRole-1R3ESR5ENZML3
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::697533197703:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-28T13:21:46Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1648"
  uid: 36d5e3bc-973f-4d49-afae-ad75a7fba770